package application.app.com.greenDao_test1.daoEntity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import application.app.com.greenDao_test1.daoEntity.Datos;

import application.app.com.greenDao_test1.daoEntity.DatosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig datosDaoConfig;

    private final DatosDao datosDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        datosDaoConfig = daoConfigMap.get(DatosDao.class).clone();
        datosDaoConfig.initIdentityScope(type);

        datosDao = new DatosDao(datosDaoConfig, this);

        registerDao(Datos.class, datosDao);
    }
    
    public void clear() {
        datosDaoConfig.clearIdentityScope();
    }

    public DatosDao getDatosDao() {
        return datosDao;
    }

}
